version: "3"

services:
  db:
    image: postgres:14
    #restart: unless-stopped
    ports:
      - 1432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./varlibpostgresqldatapgdata:/var/lib/postgresql/data/pgdata
  web:
    image: odoo:15
    #restart: unless-stopped
    volumes:
      - ./etcodoo:/etc/odoo
      - ./mntextraaddons:/mnt/extra-addons
      - ./varlibodoo:/var/lib/odoo
    ports:
      - 1569:8069
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
#    depends_on:
#      - "db"

#volumes:
#  varlibpostgresqldata:
#  varlibodoo: